In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df=pd.read_csv('archive.zip',encoding='ISO-8859-1')

In [6]:
df.head(10)

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,,NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,#Homecoming,(2021),90 min,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,...And Once Again,(2010),105 min,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali
5,...Aur Pyaar Ho Gaya,(1997),147 min,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
6,...Yahaan,(2005),142 min,"Drama, Romance, War",7.4,"1,086",Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
7,.in for Motion,(2008),59 min,Documentary,NaN,NaN,Anirban Datta,NaN,NaN,NaN
8,?: A Question Mark,(2012),82 min,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia
9,@Andheri,(2014),116 min,"Action, Crime, Thriller",4.0,11,Biju Bhaskar Nair,Augustine,Fathima Babu,Byon

In [7]:
df.shape

(15509, 10)

In [8]:
df.describe()

            Rating
count  7919.000000
mean      5.841621
std       1.381777
min       1.100000
25%       4.900000
50%       6.000000
75%       6.800000
max      10.000000

In [9]:
df.isna().sum()

Name           0
Year         528
Duration    8269
Genre       1877
Rating      7590
Votes       7589
Director     525
Actor 1     1617
Actor 2     2384
Actor 3     3144
dtype: int64

In [10]:
df.dropna(inplace=True)

In [11]:
df.isnull().sum()

Name        0
Year        0
Duration    0
Genre       0
Rating      0
Votes       0
Director    0
Actor 1     0
Actor 2     0
Actor 3     0
dtype: int64

In [12]:
df['Year'].head()

1    (2019)
3    (2019)
5    (1997)
6    (2005)
8    (2012)
Name: Year, dtype: object

In [13]:
genre=df['Genre']

In [14]:
genre.head()

1                        Drama
3              Comedy, Romance
5       Comedy, Drama, Musical
6          Drama, Romance, War
8    Horror, Mystery, Thriller
Name: Genre, dtype: object

In [16]:
genre_counts = {}
for genre in genre.values.flatten():
    if genre is not None:
        if genre in genre_counts:
            genre_counts[genre] += 1
        else:
            genre_counts[genre] = 1

genereCounts = {genre: count for genre, count in sorted(genre_counts.items())}
for genre, count in genereCounts.items():
    print(f"{genre}: {count}")

Action: 170
Action, Adventure: 17
Action, Adventure, Biography: 1
Action, Adventure, Comedy: 37
Action, Adventure, Crime: 9
Action, Adventure, Drama: 43
Action, Adventure, Family: 2
Action, Adventure, Fantasy: 11
Action, Adventure, History: 1
Action, Adventure, Horror: 1
Action, Adventure, Musical: 3
Action, Adventure, Mystery: 1
Action, Adventure, Romance: 5
Action, Adventure, Sci-Fi: 6
Action, Adventure, Thriller: 18
Action, Biography, Crime: 8
Action, Biography, Drama: 12
Action, Comedy: 24
Action, Comedy, Crime: 74
Action, Comedy, Drama: 118
Action, Comedy, Fantasy: 4
Action, Comedy, Horror: 1
Action, Comedy, Musical: 7
Action, Comedy, Mystery: 2
Action, Comedy, Romance: 27
Action, Comedy, Thriller: 6
Action, Comedy, War: 1
Action, Crime: 18
Action, Crime, Drama: 329
Action, Crime, Family: 1
Action, Crime, Fantasy: 1
Action, Crime, History: 1
Action, Crime, Horror: 1
Action, Crime, Musical: 3
Action, Crime, Mystery: 4
Action, Crime, Romance: 10
Action, Crime, Sci-Fi: 1
Action, Crime, Thriller: 45
Action, Drama: 206
Action, Drama, Crime: 2
Action, Drama, Family: 12
Action, Drama, Fantasy: 10
Action, Drama, History: 18
Action, Drama, Horror: 4
Action, Drama, Music: 5
Action, Drama, Musical: 30
Action, Drama, Mystery: 10
Action, Drama, Romance: 107
Action, Drama, Sport: 10
Action, Drama, Thriller: 49
Action, Drama, War: 6
Action, Drama, Western: 1
Action, Family: 2
Action, Family, Drama: 1
Action, Family, Mystery: 1
Action, Fantasy: 3
Action, Fantasy, Horror: 1
Action, Fantasy, Musical: 1
Action, Fantasy, Mystery: 1
Action, Fantasy, Sci-Fi: 1
Action, Fantasy, Thriller: 4
Action, History: 1
Action, Horror, Mystery: 1
Action, Horror, Sci-Fi: 2
Action, Musical: 1
Action, Musical, Romance: 8
Action, Musical, Thriller: 2
Action, Musical, War: 1
Action, Mystery: 5
Action, Mystery, Romance: 3
Action, Mystery, Thriller: 4
Action, Romance: 25
Action, Romance, Comedy: 1
Action, Romance, Drama: 1
Action, Romance, Thriller: 10
Action, Sci-Fi: 2
Action, Sci-Fi, Thriller: 2
Action, Thriller: 70
Action, Thriller, Crime: 1
Action, Thriller, Mystery: 1
Action, Thriller, Romance: 1
Action, Thriller, War: 1
Action, War: 1
Adventure: 14
Adventure, Biography, Drama: 2
Adventure, Biography, History: 1
Adventure, Comedy, Crime: 5
Adventure, Comedy, Drama: 17
Adventure, Comedy, Family: 1
Adventure, Comedy, Romance: 1
Adventure, Crime, Drama: 2
Adventure, Drama: 5
Adventure, Drama, Family: 7
Adventure, Drama, Fantasy: 10
Adventure, Drama, History: 5
Adventure, Drama, Music: 1
Adventure, Drama, Musical: 3
Adventure, Drama, Mystery: 3
Adventure, Drama, Romance: 3
Adventure, Drama, Sci-Fi: 1
Adventure, Drama, Thriller: 6
Adventure, Family, Fantasy: 2
Adventure, Fantasy: 4
Adventure, Fantasy, Romance: 2
Adventure, History, Thriller: 1
Adventure, Horror, Mystery: 3
Adventure, Horror, Romance: 1
Adventure, Mystery, Thriller: 1
Adventure, Romance: 1
Adventure, Thriller: 3
Animation: 11
Animation, Action: 1
Animation, Action, Adventure: 7
Animation, Action, Comedy: 1
Animation, Action, Drama: 1
Animation, Adventure, Comedy: 2
Animation, Adventure, Family: 3
Animation, Adventure, Fantasy: 2
Animation, Comedy, Drama: 1
Animation, Comedy, Family: 1
Animation, Drama, Adventure: 1
Animation, Drama, History: 1
Animation, Drama, Musical: 1
Animation, Drama, Romance: 1
Animation, Family: 4
Animation, Family, History: 1
Animation, Family, Musical: 1
Biography: 7
Biography, Comedy, Drama: 5
Biography, Crime, Drama: 4
Biography, Crime, Thriller: 1
Biography, Drama: 30
Biography, Drama, Family: 1
Biography, Drama, History: 16
Biography, Drama, Music: 1
Biography, Drama, Musical: 2
Biography, Drama, Romance: 3
Biography, Drama, Sport: 6
Biography, Drama, Thriller: 2
Biography, Drama, War: 2
Biography, Family: 1
Biography, History: 3
Comedy: 187
Comedy, Action: 1
Comedy, Crime: 10
Comedy, Crime, Drama: 53
Comedy, Crime, Family: 1
Comedy, Crime, Musical: 1
Comedy, Crime, Mystery: 3
Comedy, Crime, Romance: 3
Comedy, Crime, Thriller: 4
Comedy, Drama: 205
Comedy, Drama, Family: 50
Comedy, Drama, Fantasy: 14
Comedy, Drama, History: 1
Comedy, Drama, Horror: 4
Comedy, Drama, Music: 7
Comedy, Drama, Musical: 45
Comedy, Drama, Mystery: 2
Comedy, Drama, Romance: 188
Comedy, Drama, Sci-Fi: 1
Comedy, Drama, Sport: 2
Comedy, Drama, Thriller: 11
Comedy, Family: 8
Comedy, Family, Fantasy: 3
Comedy, Family, Musical: 1
Comedy, Family, Romance: 2
Comedy, Family, Sci-Fi: 1
Comedy, Fantasy: 3
Comedy, Fantasy, Musical: 1
Comedy, Fantasy, Romance: 2
Comedy, Horror: 6
Comedy, Horror, Musical: 1
Comedy, Horror, Mystery: 2
Comedy, Music: 1
Comedy, Music, Romance: 2
Comedy, Musical: 3
Comedy, Musical, Action: 1
Comedy, Musical, Drama: 1
Comedy, Musical, Mystery: 2
Comedy, Musical, Romance: 19
Comedy, Mystery: 2
Comedy, Mystery, Romance: 2
Comedy, Mystery, Thriller: 1
Comedy, Romance: 107
Comedy, Romance, Musical: 2
Comedy, Romance, Sci-Fi: 1
Comedy, Romance, Thriller: 5
Comedy, Sci-Fi: 1
Comedy, Sport: 1
Comedy, Thriller: 13
Comedy, War: 2
Crime: 24
Crime, Drama: 46
Crime, Drama, Family: 4
Crime, Drama, History: 1
Crime, Drama, Horror: 2
Crime, Drama, Music: 3
Crime, Drama, Musical: 8
Crime, Drama, Mystery: 49
Crime, Drama, Romance: 25
Crime, Drama, Thriller: 53
Crime, Fantasy, Mystery: 1
Crime, Horror, Mystery: 1
Crime, Horror, Romance: 1
Crime, Horror, Thriller: 1
Crime, Musical, Mystery: 1
Crime, Musical, Romance: 1
Crime, Musical, Thriller: 1
Crime, Mystery: 5
Crime, Mystery, Romance: 2
Crime, Mystery, Thriller: 10
Crime, Romance: 2
Crime, Romance, Thriller: 4
Crime, Thriller: 26
Documentary: 25
Documentary, Biography: 1
Documentary, Biography, Crime: 2
Documentary, Biography, Drama: 3
Documentary, Biography, Musical: 1
Documentary, Crime, History: 1
Documentary, Drama: 5
Documentary, Family: 1
Documentary, Family, History: 1
Documentary, History: 4
Documentary, History, News: 1
Documentary, Music: 1
Documentary, Sport: 1
Documentary, Thriller: 1
Drama: 844
Drama, Action, Comedy: 3
Drama, Action, Crime: 2
Drama, Action, Horror: 1
Drama, Action, Musical: 1
Drama, Adventure, Action: 2
Drama, Comedy, Action: 1
Drama, Comedy, Family: 3
Drama, Crime: 1
Drama, Crime, Mystery: 1
Drama, Family: 160
Drama, Family, Action: 2
Drama, Family, Comedy: 1
Drama, Family, Fantasy: 6
Drama, Family, History: 1
Drama, Family, Horror: 1
Drama, Family, Music: 5
Drama, Family, Musical: 18
Drama, Family, Mystery: 1
Drama, Family, Romance: 32
Drama, Family, Sport: 3
Drama, Family, Thriller: 2
Drama, Fantasy: 8
Drama, Fantasy, History: 1
Drama, Fantasy, Horror: 2
Drama, Fantasy, Musical: 3
Drama, Fantasy, Mystery: 3
Drama, Fantasy, Romance: 5
Drama, Fantasy, Sci-Fi: 1
Drama, Fantasy, Thriller: 3
Drama, Fantasy, War: 1
Drama, History: 17
Drama, History, Musical: 2
Drama, History, Romance: 6
Drama, History, Sport: 1
Drama, History, Thriller: 1
Drama, History, War: 4
Drama, Horror: 3
Drama, Horror, Musical: 3
Drama, Horror, Mystery: 15
Drama, Horror, Romance: 5
Drama, Horror, Thriller: 7
Drama, Music: 13
Drama, Music, Musical: 4
Drama, Music, Romance: 6
Drama, Musical: 21
Drama, Musical, Family: 3
Drama, Musical, Mystery: 4
Drama, Musical, Romance: 93
Drama, Musical, Sport: 1
Drama, Musical, Thriller: 1
Drama, Mystery: 11
Drama, Mystery, Romance: 13
Drama, Mystery, Sci-Fi: 1
Drama, Mystery, Thriller: 31
Drama, Romance: 332
Drama, Romance, Family: 2
Drama, Romance, Musical: 4
Drama, Romance, Sport: 1
Drama, Romance, Thriller: 40
Drama, Romance, War: 5
Drama, Sci-Fi: 2
Drama, Sport: 12
Drama, Thriller: 52
Drama, Thriller, Action: 2
Drama, War: 6
Family: 28
Family, Comedy: 1
Family, Drama: 6
Family, Drama, Thriller: 1
Family, Music, Romance: 1
Family, Musical, Romance: 4
Family, Romance: 9
Family, Romance, Drama: 1
Family, Thriller: 1
Fantasy: 21
Fantasy, Drama: 2
Fantasy, Horror: 2
Fantasy, Horror, Mystery: 1
Fantasy, Horror, Romance: 1
Fantasy, Musical, Mystery: 1
Fantasy, Mystery, Romance: 1
Fantasy, Romance: 1
Fantasy, Thriller, Action: 1
History: 6
History, Musical, Romance: 1
History, Romance: 1
Horror: 74
Horror, Drama, Mystery: 1
Horror, Mystery: 13
Horror, Mystery, Romance: 5
Horror, Mystery, Thriller: 9
Horror, Romance: 3
Horror, Romance, Sci-Fi: 1
Horror, Romance, Thriller: 3
Horror, Sci-Fi, Thriller: 1
Horror, Thriller: 18
Music: 1
Music, Romance: 2
Musical: 9
Musical, Action, Drama: 3
Musical, Comedy, Drama: 1
Musical, Comedy, Romance: 2
Musical, Drama: 4
Musical, Drama, Comedy: 1
Musical, Drama, Crime: 1
Musical, Drama, Family: 7
Musical, Drama, Romance: 8
Musical, Family, Drama: 1
Musical, Fantasy: 1
Musical, Mystery, Drama: 2
Musical, Mystery, Thriller: 2
Musical, Romance: 40
Musical, Romance, Drama: 2
Musical, Romance, Thriller: 4
Musical, Thriller: 1
Musical, Thriller, Mystery: 1
Mystery: 19
Mystery, Musical, Romance: 1
Mystery, Romance: 2
Mystery, Romance, Musical: 1
Mystery, Romance, Thriller: 5
Mystery, Sci-Fi: 1
Mystery, Sci-Fi, Thriller: 1
Mystery, Thriller: 29
Romance: 126
Romance, Action, Crime: 1
Romance, Action, Drama: 1
Romance, Comedy: 2
Romance, Comedy, Drama: 3
Romance, Drama: 6
Romance, Drama, Family: 2
Romance, Musical, Action: 1
Romance, Musical, Comedy: 1
Romance, Musical, Drama: 1
Romance, Sci-Fi, Thriller: 1
Romance, Thriller: 12
Romance, Thriller, Mystery: 2
Sci-Fi: 3
Sci-Fi, Thriller: 1
Sport: 2
Thriller: 84
Thriller, Action: 1
Thriller, Musical, Mystery: 1
Thriller, Mystery: 2
Thriller, Mystery, Family: 1
War: 3

In [18]:
genrepie=df['Genre'].value_counts()

In [19]:
genrepie.head()

Genre
Drama                   844
Drama, Romance          332
Action, Crime, Drama    329
Action, Drama           206
Comedy, Drama           205
Name: count, dtype: int64

In [ ]:
genrespie=pd.df(list(genrepie.items())